# Sample StorageClass for EFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${efs_file_system_id}
  directoryPerms: "0755"
---
# Sample PersistentVolumeClaim using EFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
# Sample Pod using EFS volume
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  namespace: default
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
    - name: efs-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-pvc
